language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: TdTNv9yKzvDjVLB3TgwQzInFyHT62DYfvjQNhnnBj9K2aubt34PLiXIlJQIYlxqOTRJSnr6+vrog9oJaTVWTdPyIMFOq6ojtgeyPUyrI+4t45X0eBF3qCTPHx38lvDW7BNK8UbAt6BaD5y6iVmlkOalgP2xa0BS8JCBbaJpn2YwD6wtyjrUwHxjEwQd5fMSTXN3okaJn5oqziLbi01mGpWCm6rtkpdaz4IlB04/LhE7qbbraKG5yoeZnzrBkPxw2uy0XsiJNZqYsEzX89e7DXtO5mSU8Zjzw1Ka/mM51nEIGn5orddHO3/7fnWtb1LMF/SRu0+aQuFz4YmtcsJLc39viSa/CefKgbp2cdjlbaAcMjVAg90WHFqV7/4Fefr2NnFugcFOPQUe4MvKW6Y5+2P7lZFuYHWUD7HBnJWHGsR7EROfc60QvK+P9Ee2iGvvnnMW6gZjhZbAkkQ2lB6CJlXX/ZMewTwHoAMvUVwPk7Rlt1e9m+LhOODqu+1LaVNsAlqPh3tQImsNMRD/yq4VH38cYC6Fa5CU94OyAk4mxDZE/CyeKXk9VIH3qXUNNbdEb9Unah2DZWP1lQQwmEOHpHHy5dV2f07cTkuW7UHmK8dah1UIa08DOSOIYReZDPVv3GY6HjC0YkDLNQdEpsol9RddjfAXGTpd/ukBx1i6wK3w=
  app: sample-travis-heroku
  on:
    repo: Treudey/sample-travis-heroku
